# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user interface.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(504, 572)
        MainWindow.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(310, 10, 151, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"font: 75 14pt \"DejaVu Sans\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"font: 75 14pt \"DejaVu Sans\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 191, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scorelabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.scorelabel.setFont(font)
        self.scorelabel.setStyleSheet("font: 75 28pt \"DejaVu Sans\";\n"
"")
        self.scorelabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scorelabel.setLineWidth(3)
        self.scorelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.scorelabel.setObjectName("scorelabel")
        self.verticalLayout.addWidget(self.scorelabel)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 42))
        self.label.setStyleSheet("font: 12pt \"DejaVu Sans\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gamepanel = QtWidgets.QFrame(self.centralwidget)
        self.gamepanel.setGeometry(QtCore.QRect(6, 110, 491, 351))
        self.gamepanel.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.gamepanel.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.gamepanel.setFrameShape(QtWidgets.QFrame.Box)
        self.gamepanel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.gamepanel.setLineWidth(4)
        self.gamepanel.setObjectName("gamepanel")
        self.gridLayoutWidget = QtWidgets.QWidget(self.gamepanel)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 471, 331))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.key00 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.key00.setStyleSheet("font: 75 24pt \"DejaVu Sans\";\n"
"background-color: rgb(170, 146, 89);")
        self.key00.setFrameShape(QtWidgets.QFrame.Box)
        self.key00.setLineWidth(2)
        self.key00.setMidLineWidth(1)
        self.key00.setText("")
        self.key00.setIndent(-1)
        self.key00.setObjectName("key00")
        self.gridLayout.addWidget(self.key00, 0, 0, 1, 1)
        self.key10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.key10.setStyleSheet("font: 75 24pt \"DejaVu Sans\";\n"
"background-color: rgb(170, 146, 89);")
        self.key10.setFrameShape(QtWidgets.QFrame.Box)
        self.key10.setLineWidth(2)
        self.key10.setText("")
        self.key10.setObjectName("key10")
        self.gridLayout.addWidget(self.key10, 1, 0, 1, 1)
        self.key20 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.key20.setStyleSheet("font: 75 24pt \"DejaVu Sans\";\n"
"background-color: rgb(170, 146, 89);")
        self.key20.setFrameShape(QtWidgets.QFrame.Box)
        self.key20.setLineWidth(2)
        self.key20.setText("")
        self.key20.setObjectName("key20")
        self.gridLayout.addWidget(self.key20, 2, 0, 1, 1)
        self.key30 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.key30.setStyleSheet("font: 75 24pt \"DejaVu Sans\";\n"
"background-color: rgb(170, 146, 89);")
        self.key30.setFrameShape(QtWidgets.QFrame.Box)
        self.key30.setLineWidth(2)
        self.key30.setText("")
        self.key30.setObjectName("key30")
        self.gridLayout.addWidget(self.key30, 3, 0, 1, 1)
        self.key11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.key11.setStyleSheet("font: 75 24pt \"DejaVu Sans\";\n"
"background-color: rgb(170, 146, 89);")
        self.key11.setFrameShape(QtWidgets.QFrame.Box)
        self.key11.setLineWidth(2)
        self.key11.setText("")
        self.key11.setObjectName("key11")
        self.gridLayout.addWidget(self.key11, 1, 1, 1, 1)
        self.key01 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.key01.setStyleSheet("background-color: rgb(170, 146, 89);\n"
"font: 75 24pt \"DejaVu Sans\";\n"
"background-color: rgb(170, 146, 89);")
        self.key01.setFrameShape(QtWidgets.QFrame.Box)
        self.key01.setLineWidth(2)
        self.key01.setText("")
        self.key01.setObjectName("key01")
        self.gridLayout.addWidget(self.key01, 0, 1, 1, 1)
        self.key31 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.key31.setStyleSheet("font: 75 24pt \"DejaVu Sans\";\n"
"background-color: rgb(170, 146, 89);")
        self.key31.setFrameShape(QtWidgets.QFrame.Box)
        self.key31.setLineWidth(2)
        self.key31.setText("")
        self.key31.setObjectName("key31")
        self.gridLayout.addWidget(self.key31, 3, 1, 1, 1)
        self.key12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.key12.setStyleSheet("font: 75 24pt \"DejaVu Sans\";\n"
"background-color: rgb(170, 146, 89);")
        self.key12.setFrameShape(QtWidgets.QFrame.Box)
        self.key12.setLineWidth(2)
        self.key12.setText("")
        self.key12.setObjectName("key12")
        self.gridLayout.addWidget(self.key12, 1, 2, 1, 1)
        self.key13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.key13.setStyleSheet("font: 75 24pt \"DejaVu Sans\";\n"
"background-color: rgb(170, 146, 89);")
        self.key13.setFrameShape(QtWidgets.QFrame.Box)
        self.key13.setLineWidth(2)
        self.key13.setText("")
        self.key13.setObjectName("key13")
        self.gridLayout.addWidget(self.key13, 1, 3, 1, 1)
        self.key02 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.key02.setStyleSheet("font: 75 24pt \"DejaVu Sans\";\n"
"background-color: rgb(170, 146, 89);")
        self.key02.setFrameShape(QtWidgets.QFrame.Box)
        self.key02.setLineWidth(2)
        self.key02.setText("")
        self.key02.setObjectName("key02")
        self.gridLayout.addWidget(self.key02, 0, 2, 1, 1)
        self.key03 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.key03.setStyleSheet("font: 75 24pt \"DejaVu Sans\";\n"
"background-color: rgb(170, 146, 89);")
        self.key03.setFrameShape(QtWidgets.QFrame.Box)
        self.key03.setLineWidth(2)
        self.key03.setText("")
        self.key03.setObjectName("key03")
        self.gridLayout.addWidget(self.key03, 0, 3, 1, 1)
        self.key22 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.key22.setStyleSheet("font: 75 24pt \"DejaVu Sans\";\n"
"background-color: rgb(170, 146, 89);")
        self.key22.setFrameShape(QtWidgets.QFrame.Box)
        self.key22.setLineWidth(2)
        self.key22.setText("")
        self.key22.setObjectName("key22")
        self.gridLayout.addWidget(self.key22, 2, 2, 1, 1)
        self.key33 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.key33.setStyleSheet("font: 75 24pt \"DejaVu Sans\";\n"
"background-color: rgb(170, 146, 89);")
        self.key33.setFrameShape(QtWidgets.QFrame.Box)
        self.key33.setLineWidth(2)
        self.key33.setText("")
        self.key33.setObjectName("key33")
        self.gridLayout.addWidget(self.key33, 3, 3, 1, 1)
        self.key32 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.key32.setStyleSheet("font: 75 24pt \"DejaVu Sans\";\n"
"background-color: rgb(170, 146, 89);")
        self.key32.setFrameShape(QtWidgets.QFrame.Box)
        self.key32.setLineWidth(2)
        self.key32.setText("")
        self.key32.setObjectName("key32")
        self.gridLayout.addWidget(self.key32, 3, 2, 1, 1)
        self.key23 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.key23.setStyleSheet("font: 75 24pt \"DejaVu Sans\";\n"
"background-color: rgb(170, 146, 89);")
        self.key23.setFrameShape(QtWidgets.QFrame.Box)
        self.key23.setLineWidth(2)
        self.key23.setText("")
        self.key23.setObjectName("key23")
        self.gridLayout.addWidget(self.key23, 2, 3, 1, 1)
        self.key21 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.key21.setStyleSheet("font: 75 24pt \"DejaVu Sans\";\n"
"background-color: rgb(170, 146, 89);")
        self.key21.setFrameShape(QtWidgets.QFrame.Box)
        self.key21.setLineWidth(2)
        self.key21.setText("")
        self.key21.setObjectName("key21")
        self.gridLayout.addWidget(self.key21, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 480, 271, 61))
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(350, 490, 101, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("alternate-background-color: rgb(170, 170, 0);\n"
"font: 12pt \"DejaVu Sans\";\n"
"background-color: rgb(170, 170, 127);")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 504, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "2048"))
        self.label_2.setText(_translate("MainWindow", "Score  0"))
        self.label_3.setText(_translate("MainWindow", "Best   0"))
        self.scorelabel.setText(_translate("MainWindow", "2048"))
        self.label.setText(_translate("MainWindow", "move and merge the numers for 2048"))
        self.label_4.setText(_translate("MainWindow", "Tips: press up, down, left or right to move the blocks. Two blocks will merge if they are neighbors and have the same number."))
        self.pushButton.setText(_translate("MainWindow", "New Game"))

